version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "MichalMalyska"
    groups:
      dev-deps:
        patterns:
          - "ruff"
          - "pytest"
          - "pre-commit"
      all-other-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "MichalMalyska"
    groups:
      all-github-actions:
        patterns:
          - "*"
