repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-json
- repo: https://github.com/milin/gitown
  rev: v0.1.7
  hooks:
  - id:  gitown
    args: ['--ownership_threshold=25', '--codeowners_filename=CODEOWNERS']
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.5
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
